/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import java.util.List;

import org.apache.log4j.Logger;

import com.itt.tds.logging.TDSLogger;
import com.itt.tds.client.ConfigGenerator;
import com.itt.tds.client.Query;
import com.itt.tds.client.Queue;
import com.itt.tds.client.Result;

import picocli.CommandLine;
import picocli.CommandLine.*;

@Command(description = "A multi-node Task executer", mixinStandardHelpOptions = true, // auto-include --help and --version
		subcommands = { Queue.class, Query.class, Result.class, ConfigGenerator.class })
public class Taskmgr implements Runnable {
	static Logger logger = new TDSLogger().getLogger();

	public static void main(String[] args) {
		Taskmgr app = new Taskmgr();
		if (args.length == 0)
			CommandLine.usage(app, System.out);
			
		@SuppressWarnings("unused")
		List<Object> result = new CommandLine(app).parseWithHandler(new RunAll(), args);
	}

	@Override
	public void run() {

	}

}
