/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

public class Taskmgr {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new Taskmgr().getGreeting());
        com.itt.tds.client.Client.main(args);
    }
}
