/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package node;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        if (args.length > 0)
        {
        System.out.println("Your first argument is: "+args[0]);  
        }
    }
}
