/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package node;

import java.util.List;

import org.apache.log4j.Level;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

import com.itt.tds.logging.TDSLogger;
import com.itt.tds.node.ConfigGenerator;
import com.itt.tds.node.InitializeNode;
import com.itt.tds.node.NodeConfiguration;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.RunAll;

@Command(description = "Act as a node for multi-node task executor", mixinStandardHelpOptions = true, subcommands = {
		InitializeNode.class, ConfigGenerator.class})
public class App implements Runnable {

	static Logger logger = new TDSLogger().getLogger();

	public static void main(String[] args) {
		NodeConfiguration nodeCfg = NodeConfiguration.getInstance();
		Level logLevel = Level.toLevel(nodeCfg.getLogLevel());
		LogManager.getRootLogger().setLevel(logLevel);

		App app = new App();
		if (args.length == 0)
			CommandLine.usage(app, System.out);

		@SuppressWarnings("unused")
		List<Object> result = new CommandLine(app).parseWithHandler(new RunAll(), args);
	}

	@Override
	public void run() {
	}
}
