/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.itt.tds.cfg.TDSConfiguration;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        
        TDSConfiguration tdsCFG = TDSConfiguration.getInstance();
        String connectionURL = tdsCFG.getDBConnectionString();
        System.out.println(connectionURL);
        
    }
}
