import java.util.List;

import org.apache.log4j.Logger;

import com.itt.tds.cfg.ConfigGenerator;
import com.itt.tds.coordinator.Server;
import com.itt.tds.logging.TDSLogger;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Command(description = "A multi-node Task executer Server", mixinStandardHelpOptions = true, // auto-include --help and
																								// --version
		subcommands = { Server.class, ConfigGenerator.class })
public class App implements Runnable {
	
	static Logger logger = new TDSLogger().getLogger();

	public static void main(String[] args) throws Exception {
		App app = new App();
		if (args.length == 0)
			CommandLine.usage(app, System.out);		

		@SuppressWarnings("unused")
		List<Object> result = new CommandLine(app).parseWithHandler(new RunAll(), args);

	}

	@Override
	public void run() {
		// TODO Auto-generated method stub

	}
}
