/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import org.junit.Test;
import static org.junit.Assert.*;

public class TaskmgrTest {
    @Test public void testAppHasAGreeting() {
        Taskmgr classUnderTest = new Taskmgr();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
